Fixes #18180: Make rtf handle network hostonly uniqueness
Normation/rudder-tests pull request #254
Opened 2020-09-09 09:47 UTC by Fdall

https://issues.rudder.io/issues/18180

2020-09-09 12:01 UTC, peckpeck commented on lib/platform.py
> +    return ("192.168.%s.0"%(pf_id), "255.255.255.0")
the base network can be defines in the Vagrantfile, so you shouldn't hardcode 192.168. here an the mask is also in the Vagrantfile (see $NETWORK)

2020-09-09 12:03 UTC, peckpeck requested changes
Use $NERWORK

2020-09-09 13:20 UTC, Fdall commented
PR updated with a new commit

2020-09-09 13:38 UTC, peckpeck commented on lib/platform.py
> +        m = re.match("^\$NETWORK=[\'\"](.*)[\'\"]", line)
\s* are needed around =

2020-09-09 13:47 UTC, Fdall commented
PR updated with a new commit

2020-09-09 14:09 UTC, Fdall commented
PR updated with a new commit

2020-09-09 14:37 UTC, peckpeck approved these changes

2020-09-10 09:31 UTC, peckpeck approved these changes

2020-09-10 14:47 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2020-09-10 14:47 UTC, merged